spring:
  application:
    name: API-
  cloud:
    gateway:
      routes:
        - id: USER-SERVICE
          uri: lb://USER-SERVICE
          predicates:
            - Path=/users/**
        - id: DEPT-SERVICE
          uri: lb://DEPT-SERVICE
          predicates:
            - Path=/dept/**

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
#    prefer-ip-address: true


server:
  port: 9191