spring:
  application:
    name: USER-SERVICE
  h2:
    console:
      enabled: true
  datasource:
    url: jdbc:h2:mem:userdb
    username: sa
    password:
    driverClassName: org.h2.Driver

#eureka:
#  client:
#    registerWithEureka: true
#    fetchRegistry: true
#    serviceUrl:
#      defaultZone: http://localhost:8761/eureka
#  instance:
#    hostname: localhost
#    prefer-ip-address: true

server:
  port: 8080

