server:
  port: 9090

spring:
  application:
    name: ZIPKIN-SERVER
  cloud:
    config:
      name: zipkin
      discovery:
        sevice-id: config
        enabled: true
      username: configUser
      password: configPassword